//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/SampleControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SampleControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SampleControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SampleControls"",
    ""maps"": [
        {
            ""name"": ""MusicPlayer"",
            ""id"": ""f960604f-b939-46d6-96f6-72dca0692156"",
            ""actions"": [
                {
                    ""name"": ""Next"",
                    ""type"": ""Button"",
                    ""id"": ""c17baebd-cb63-4828-aea7-43b2e5430815"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dc558827-c8d0-4219-8e58-f7b59fa1a9ed"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MusicPlayer
        m_MusicPlayer = asset.FindActionMap("MusicPlayer", throwIfNotFound: true);
        m_MusicPlayer_Next = m_MusicPlayer.FindAction("Next", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MusicPlayer
    private readonly InputActionMap m_MusicPlayer;
    private List<IMusicPlayerActions> m_MusicPlayerActionsCallbackInterfaces = new List<IMusicPlayerActions>();
    private readonly InputAction m_MusicPlayer_Next;
    public struct MusicPlayerActions
    {
        private @SampleControls m_Wrapper;
        public MusicPlayerActions(@SampleControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Next => m_Wrapper.m_MusicPlayer_Next;
        public InputActionMap Get() { return m_Wrapper.m_MusicPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MusicPlayerActions set) { return set.Get(); }
        public void AddCallbacks(IMusicPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_MusicPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MusicPlayerActionsCallbackInterfaces.Add(instance);
            @Next.started += instance.OnNext;
            @Next.performed += instance.OnNext;
            @Next.canceled += instance.OnNext;
        }

        private void UnregisterCallbacks(IMusicPlayerActions instance)
        {
            @Next.started -= instance.OnNext;
            @Next.performed -= instance.OnNext;
            @Next.canceled -= instance.OnNext;
        }

        public void RemoveCallbacks(IMusicPlayerActions instance)
        {
            if (m_Wrapper.m_MusicPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMusicPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_MusicPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MusicPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MusicPlayerActions @MusicPlayer => new MusicPlayerActions(this);
    public interface IMusicPlayerActions
    {
        void OnNext(InputAction.CallbackContext context);
    }
}
